### ISSUE TITLE
Missing items from RWOT Primer

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/rwot12-cologne#1]
https://github.com/WebOfTrustInfo/rwot12-cologne/blob/main/advance-readings/rwot-primer.md

It doesn't mention Poster Night (evening before day 1) Demo Night (day 2).

May be missing some other minor items. 

/cc @jandrieu

**Comment by shannona** [comment]
Poster Night and Demo Night were both in there, but I've gone the whole piece, updated with our current language, and clarified. Should be ready for RWOT12.
