### ISSUE TITLE
I'm not github literate, can you enter an advance reading topic for me?

### ISSUE THREAD

**Issue by mosestma** [WebOfTrustInfo/rwot12-cologne#7]
Please accept our contribution to the RWOT 12 workshop.

### Decentralized Identity and Verifiable Claims for the Arts and Artists (link)
* by Gaya Blair Pendleton, Valerie Brusola, Markus Willms, and [Moses Ma](mailto:moses.ma@futurelabconsulting.com)  
* Articulating the principles and key design considerations for a use case for DIDs and VCs in the world of fine arts involving both physical and digital collectibles
* #did #vc #verifiablecredentials #supplychain #dpp

Submitted to the 12th Rebooting the Web of Trust Technical Workshop
September 18-22, 2023 • Cologne, Germany

**Keywords:** decentralization, art, verified claims, identity, blockchain, decentralized, self-sovereign, NFT, dynamic tokens

**PROPOSAL**

We propose to facilitate the collaborative drafting of a technical paper that describes the principles and key design considerations for a use case for DIDs and VCs in the world of fine arts involving both physical and digital collectibles. Theart world needs a simplification of DID terminology in order to better understand the "decentralization revolution" and to better participate in the development of game-changing decentralized business models for the art world. We believe that collaborative efforts at RWOT12 between technologists and artists could provide a tipping point for the thoughtful adoption of DIDs and VCs in the art world.

We base much of our work on key design considerations for decentralized identity, claims and reputation, developed by C. Allen, M. Sporny, D. Reed, and many others (see references), at previous RWOT design conferences.

**BACKGROUND**

First, the era of NFTs as _inert collectible_ is now over. We believe that integrating technologies like DID and Verifiable Credentials will help to create new kinds of smart digital tokens that will replace NFTs, and provide new ways to engage, sell, create value, and to increase customer loyalty. We call these new objects _BDTs_ — short for Blockchain Dynamic Tokens.

The authors are co-founders of Nidify.io, a startup which has the goal of creating BDTs that are "nestable", in which a token can own others. This recursive capacity allows for complexity with a very simple operational model. For example, in the arts, why can't a BDT of an artwork contain BDTs or NFTs of sketches, notes, drafts, maquettes and buzzettos within them? Or artist statement videos, crypto-based awards from web art shows and competitions, verifiable appraisals, celebrity endorsements, and so on? This vision includes the use of DIDs and VCs to enable greater value. Our goal is develop and deploy standards for multi-token instruments, using both nesting and trading baskets:

- Nesting is the ability for a token to own another token, or series of tokens, in order to increase their value, and to enable a simple method for increasing token complexity;
- Baskets are collections of tokens, gathered together to enable risk mitigation through diversification, which can be applied to art collections and credit default swaps;
- And we propose to leverage multi-token functionality by integrating AI and location/state intelligence to enable revolutionary new functionality for collectibles and other tokens. They can create multiple paths for value creation encompassing referrals, partnerships, and the monetization of customer loyalty.

The primary goals for our solution is to provide immutable evidence of provenance and to enable new models for artists to achieve commercial success.

**About DIDs and VCs**

The Decentralized ID movement has identified an unique opportunity to fix deep, systemic flaws in the methods that currently manage online identity. It offers new concepts for user-centric identity by givingfull user control over digital identity with VCs and DIDs, forsecure user autonomy. This means control, not just consent, presenting a smooth path to transportable self-sovereign identity services and resources.

DIDs are digital identifiers not tied to a centralized authority or organization, but registered on a decentralized network such as a blockchain, and can be used to authenticate a user's identity without relying on a third-party verification system. VCs are digital credentials used to verify information about an individual, organization, or thing. They provide a standardized way of sharing information, portable across varying platforms and systems.

Self-sovereign identity adheres to a series of guiding principlesmeant to ensure that the user controls their identity related data. Identity data is a double-edged sword — usable for both positive and negative purposes. Thus, an identity system must balance transparency, fairness, and support of the commons with protection for the individual. These principles include personhood, control, access, transparency, persistence, portability, interoperability, consent, minimization of disclosure, protection, and selectivity in disclosure.

The current embodiment of these principles have been encoded into the "Decentralized Identity specification" (DID is the acronym for the decentralized identifier). The DID spec is now being developed by a working group at the World Wide Web Consortium, known as the Credentials Community Group. DIDs provide a way for individuals and organizations to create permanent, globally unique, verifiable identifiers that are entirely under the identity owner's control. Unlike a domain name, IP address, or phone number, a DID is not rented from any service provider, and no one can take it away from whomever owns or controls the associated private key. DIDs are the first globally unique verifiable identifiers that require no registration authority.

**APPLICATION TO ART AND ARTISTS**

To be blunt, the greatest hurdle to adoption of Decentralized IDs is that they are far too difficult to understand for non-technical users. Fine artists are good examples of non-technical users, so we propose this project to better articulate how DIDs and VCs work and why they they might be useful for the arts community. We need to show how this technology, unlike NFTs, will not simply allow savvy technologist to use artists, to make money off less savvy investors.

We propose to use imagery, storytelling, music and video production to explain the value proposition more clearly. We propose to articulate, in a memorable way, why leveraging DIDs in a decentralized network can enable artists and collectors to create and manage their digital identities and authenticate their ownership of artworks. For example, the technologist would want to explain that an artist can create a DID that is associated with their digital identity, to verify their ownership of an NFT/ BDT artwork. When the artwork is sold or transferred, the new owner receives a verifiable credential authenticating their ownership of the artwork, allowing for a transparent and secure transfer of ownership easily traceable on the blockchain. However, our approach is to say something simpler that resonates emotionally, such as "The BDT has BDE" – blockchain dynamic energy – and write a song about it. 😉

**WHY THIS MATTERS**

Just as the Industrial Revolution powered the rise of Modernism, the Digital Revolution will power new movements in art. We would like to call this next emergent art movement _Decentralism_. The factors that are likely to shape decentralism will be the relentless advancement of the blockchain, the continuing growth of cryptocurrency, the formation of digital societies, climate change, pandemics, the rise of smart cities, and the rise of generative AI and quantum computing. Decentralist ideals will emerge that will not only transform art and literature, but will pervade architecture, music, philosophy, sex, marriage, urban planning, and everything we consider part of the human condition. This emergent artistic movement is likely to be based on decentralizing ideals of democracy, equality, and self-sovereign functionality, to offer a refreshing new take on the utopian vision of Modernism.

As decentralization progresses in our society, we will also see changes in how art is sold, as decentralization is essentially about removing middlemen. The emerging model for marketing art will be a bit like online dating – how does the creator of a certain kind of art find a buyer who would find it appealing? In past generations, matchmakers would connect people for marriage and art dealers and galleries matched patrons and artists. But online dating has replaced those matchmakers with algorithms, although not always with stunning success. People learned the hard way that they needed to understand how good matches are made to finetune the matching algorithms on match.com and OKcupid.

Finally, artists need to realize that you can't be timid about technology, to paraphrase the playwright Émile Zola – artists must _"live life out loud online_". What this means is that to be successful, artists need to be aggressive in the use of emerging technologies for both the creation and marketing of their art. If we look at the Cambrian Explosion, the species that survived were the ones that evolved more briskly. Art itself is an evolutionary process, and requires that artists keep pushing to improve and refine not only their artwork, but how they market and sell their art.

We need to see that humans make art like oysters make pearls. Pearls are formed when an irritant, such as a grain of sand, becomes trapped in the mollusk. To protect itself, the mollusk secretes substances that form its shell. It grows over time, forming the pearl. For an underpaid artist, things like NFTs, DIDs and generative AI can be irritants. But within this irritation holds the potential to help those artists produce even more beautiful and meaningful art.

Jean Sibelius said, "Art is the signature of civilizations." What will be the signature of the Decentralization Revolution?

**Next Steps**

Here are the deliverables we hope to develop during the workshop:

1. Develop a better understanding for how DIDs and verifiable claims would interoperate within the art world
2. Create a user personas for a typical artist and art collector to analyze tacit needs
3. Develop a use case for a BDT that uses DIDs and Verifiable Claims
4. Articulate the value model in very clear terms so the value of BDTs, DIDs and VCs can be understood at an intuitive and emotionally evocative model
5. Open discussion on other issues related to this effort

**REFERENCES**

1. https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2017/blob/master/topics-and-advance-readings/did-primer.md

**Comment by shannona** [comment]
This was done.
